# Generated by Django 3.2.6 on 2021-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsList',
            fields=[
                ('studentId', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30, null=True)),
                ('markOne', models.IntegerField()),
                ('markTwo', models.IntegerField()),
                ('markThree', models.IntegerField()),
                ('markFour', models.IntegerField()),
                ('markFive', models.IntegerField()),
            ],
        ),
    ]
